<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Release</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">x64</Platform>
    <OutputType>WinExe</OutputType>
    <AssemblyName>Pegline</AssemblyName>
    <RootNamespace>Pegline</RootNamespace>
    <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
    <LangVersion>5</LangVersion>
    <PlatformTarget>x64</PlatformTarget>
    <OutputPath>bin\</OutputPath>
    <Optimize>true</Optimize>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>assets\pegline.ico</ApplicationIcon>
    <StartupObject>Pegline.Program</StartupObject>
    <AppConfig>app.config</AppConfig>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System"/><Reference Include="System.Core"/><Reference Include="System.Drawing"/>
    <Reference Include="System.Windows.Forms"/><Reference Include="System.Runtime.Serialization"/><Reference Include="System.Xml" />
    <Reference Include="System.Xaml"/><Reference Include="UIAutomationProvider"/><Reference Include="UIAutomationTypes"/>
    <Reference Include="WindowsBase"/><Reference Include="PresentationCore"/><Reference Include="PresentationFramework"/><Reference Include="Microsoft.VisualBasic"/>
    <Compile Include="src\*.cs"/>
    <None Include="app.config"/><None Include="app.manifest"/>
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets"/>
</Project>
